# Generated by Django 5.2.8 on 2025-11-07 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Treaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(blank=True, verbose_name='PDF URL')),
                ('country1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country1_treaties', to='treaties.country')),
                ('country2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country2_treaties', to='treaties.country')),
            ],
            options={
                'verbose_name_plural': 'Treaties',
                'unique_together': {('country1', 'country2')},
            },
        ),
    ]
